---
ahoyapi: v2

commands:
  up:
    usage: Start the testing environment
    cmd: ./scripts/setup.sh start

  down:
    usage: Stop and remove the testing environment
    cmd: ./scripts/setup.sh stop

  test:
    usage: Run installer tests
    cmd: ./scripts/test.sh 