FROM uselagoon/php-8.3-cli-drupal:24.10.0

# Set environment variables for testing
ENV COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_CACHE_DIR=/tmp/.composer/cache

# Create test workspace
RUN mkdir -p /workspace

# Copy application files to workspace
COPY . /workspace

# Create test directories that would normally be created by the installer
RUN mkdir -p /workspace/tests /workspace/.circleci /workspace/.github/workflows && \
    chmod -R 0777 /workspace/tests /workspace/.circleci /workspace/.github/workflows

WORKDIR /workspace 