FROM uselagoon/php-8.3-cli-drupal:24.10.0

WORKDIR /app

# Set environment variables for testing
ENV COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_CACHE_DIR=/tmp/.composer/cache

# Copy application files
COPY . /app

# Create test directories that would normally be created by the installer
RUN mkdir -p /app/tests /app/.circleci /app/.github/workflows && \
    chmod -R 0777 /app/tests /app/.circleci /app/.github/workflows

WORKDIR /app 