version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      # Mount source code as read-only
      - .:/source:ro
      # Mount a named volume for test outputs
      - scaffold_test_workspace:/workspace
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}

volumes:
  scaffold_test_workspace:
