version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      # Mount a named volume for test outputs
      - scaffold_test_workspace:/workspace
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - SOURCE_DIR=/source
      - WORKSPACE_DIR=/workspace

volumes:
  scaffold_test_workspace:
