FROM uselagoon/php-8.3-cli-drupal:24.10.0

# Set environment variables for testing
ENV COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_CACHE_DIR=/tmp/.composer/cache \
    SOURCE_DIR=/source \
    WORKSPACE_DIR=/workspace

# Create directories
RUN mkdir -p /source /workspace

# Copy source files
COPY . /source

# Create test directories that would normally be created by the installer
RUN mkdir -p /workspace/tests /workspace/.circleci /workspace/.github/workflows && \
    chmod -R 0777 /workspace/tests /workspace/.circleci /workspace/.github/workflows && \
    cp /source/scaffold-installer.php /workspace/

WORKDIR /workspace 